services:
  android-build:
    build: .
    volumes:
      - ./signing.properties:/build/signing.properties
      - ./keystore.jks:/build/keystore.jks
      - ./app/release:/build/output
    command: >
      sh -c "
        rm -Rf __apk_build_repo__
        git clone https://github.com/KSSidll/Arru __apk_build_repo__ &&
        cp signing.properties __apk_build_repo__ &&
        cp keystore.jks __apk_build_repo__ &&
        cd __apk_build_repo__ &&
        git checkout d60393ec7bf880fb1930fd2fa41c57518302932f &&
        chmod +x ./gradlew &&
        ./gradlew clean assembleRelease --no-build-cache --no-configuration-cache --no-daemon &&
        rm -Rf /build/output/* &&
        cp -r app/build/outputs/apk/release/* /build/output
      "
